"""Model Lab: every number in the deck, regenerated by `make results`, plus model cards."""

from __future__ import annotations

import json

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from seismo.ui.common import ACCENT, MUTED, NEG, POS, WATCH, base_layout, header, settings


def load(name: str) -> dict | None:
    p = settings.root / "docs" / "results" / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def render() -> None:
    header("Model Lab", "Measured comparisons against named naive baselines. Nothing here is typed by hand: "
           "`make results` regenerates every table from the repository.")
    res = load("results.json")
    if not res:
        st.info("Run `make results` to build docs/results/results.json.")
        return
    st.caption(f"Generated {res.get('generated_at', '?')} with sentiment backend {res.get('sentiment_backend')}, "
               f"impact model {res.get('impact_model')}.")

    st.markdown("### Replay scorecard: gated trigger vs naive trigger")
    sc = pd.DataFrame(res["scorecard"])
    st.dataframe(sc, hide_index=True, width="stretch")

    c1, c2 = st.columns(2, gap="medium")
    with c1:
        st.markdown("### Corroboration and dedup")
        st.dataframe(pd.DataFrame(res["dedup"]), hide_index=True, width="stretch")
    with c2:
        st.markdown("### Gold set (entity linking, target sentiment, event class)")
        gold = res.get("gold")
        if gold:
            st.dataframe(pd.DataFrame(gold["table"]), hide_index=True, width="stretch")
            st.caption(gold.get("note", ""))

    imp = load("impact_report.json")
    st.markdown("### Impact: calibrated on 8-K event studies (|SCAR| > 2)")
    if imp:
        rep = imp["report"]
        rows = [{k: v for k, v in rep[s].items() if k != "reliability"} for s in ("train", "valid", "test", "post") if rep.get(s, {}).get("n")]
        st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch")
        rel = rep.get("test", {}).get("reliability", [])
        a, b = st.columns(2)
        if rel:
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode="lines", line={"color": MUTED, "dash": "dot"}, name="Perfect calibration"))
            fig.add_trace(go.Scatter(x=[r["predicted"] for r in rel], y=[r["observed"] for r in rel], mode="lines+markers",
                                     marker={"size": [6 + min(20, r["n"] / 10) for r in rel], "color": ACCENT}, name="Test 2022-2023"))
            base_layout(fig, "Reliability: predicted vs observed two-sigma rate (test set)", 320)
            fig.update_xaxes(title="Predicted", range=[0, 1])
            fig.update_yaxes(title="Observed", range=[0, 1])
            a.plotly_chart(fig, width="stretch", config={"displayModeBar": False})
        by = pd.DataFrame(imp.get("by_class", []))
        if not by.empty:
            by = by.sort_values("two_sigma_rate")
            fig = go.Figure(go.Bar(x=by["two_sigma_rate"], y=by["cls"], orientation="h",
                                   marker_color=[NEG if v > 0.3 else WATCH if v > 0.15 else POS for v in by["two_sigma_rate"]],
                                   text=[f"n={n}" for n in by["n"]], textposition="outside"))
            base_layout(fig, "Share of 8-K events followed by a two-sigma move, by class", 320)
            fig.update_xaxes(tickformat=".0%")
            b.plotly_chart(fig, width="stretch", config={"displayModeBar": False})
    else:
        st.caption("Needs data/market/edgar_8k.csv and prices_daily.csv: `make data` then `make impact`.")

    st.markdown("### Latency and throughput (CPU, replay at full speed)")
    st.dataframe(pd.DataFrame([res["latency"]]), hide_index=True, width="stretch")

    st.markdown("### Model and data cards")
    cards = sorted((settings.root / "models").glob("*.md")) + sorted((settings.root / "docs" / "cards").glob("*.md"))
    for p in cards:
        with st.expander(p.stem.replace("_", " ")):
            st.markdown(p.read_text(encoding="utf-8"))
